name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
      - feature/* # Add the 'make' branch to the list of branches that trigger the workflow
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure this matches the version you need
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
    # Optionally, skip deployment steps if branch is 'make'
    if: github.ref != 'refs/heads/make'

  deploy:
    needs: build-and-test
    if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && github.ref != 'refs/heads/feature/*'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Deploy to Development
        if: github.ref == 'refs/heads/develop'
        run: echo "Deploying to development environment..."
        # Replace echo with your actual deployment command/script
      
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo "Deploying to staging environment..."
        # Replace echo with your actual deployment command/script

      - name: Manual trigger for Production deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: echo "Deploying to production environment..."
        # Replace echo with your actual deployment command/script
